http:
  routers:
    outline-spaces-root:
      rule: "Host(`outline.spaces.community`) && Path(`/`)"
      entryPoints:
        - websecure
      priority: 100000
      tls:
        certResolver: letsencrypt
      service: outline-spaces-sso
    outline-spaces-sso:
      rule: "Host(`outline.spaces.community`) && PathPrefix(`/spaces-sso`)"
      entryPoints:
        - websecure
      priority: 100000
      tls:
        certResolver: letsencrypt
      service: outline-spaces-sso
  services:
    outline-spaces-sso:
      loadBalancer:
        servers:
          - url: "http://172.16.4.6:3000"
